version: '3.1'

services:
  covid_tracker:
    image: covid_tracker
    build: .
    restart: "no"
    environment:
#      - WORKSPACE=PROD  # Use PROD for publishing over internet - uses gunicorn
      - WORKSPACE=DEV
      - COMPOSE_PROJECT_NAME=covid_tracker
    env_file:
      - ./.env
    ports:
      - 9000:8000
