version: '3.1'

services:
  covid_tracker:
    image: covid_tracker
    build: .
    restart: always
    environment:
#      - WORKSPACE=PROD  # Use PROD for publishing over internet
      - WORKSPACE=DEV
      - COMPOSE_PROJECT_NAME=covid_tracker
    env_file:
      - ./.env
    ports:
      - 8000:8000
